### PR TITLE
Added samba_config() function

### PR DESCRIPTION
**Pull request by codetronaut**
Added the function samba_config().

### CODE REVIEW

**Comment by codetronaut** [comment]
@amanharitsh123 , Please review it.

**Comment by amanharitsh123** [comment]
Reviewing it for the past half an hour now. There are many bugs to be resolved. Nevermind I have fixed many of them and will be sending a commit for the same which you can have a look at to find your mistakes.

**Comment by amanharitsh123** [comment]
Merging this PR.

**Comment by codetronaut** [comment]
@amanharitsh123 , I will look into them, thanks.

**Pull request merged**
